# Введение в NumPy

NumPy предназначен для:
1. быстрых операций с векторами операции массивов для обработки и очистки данных
2. эффективной сортировки, поиска уникальных элементов и присвоения значений
3. получения описательной статистики
4. проверки согласованности данных, обработки и объединения данных
5. выражения условной логики, вместо циклов с ветвями if-elif-else
6. групповых манипуляций с данными (агрегация, трансформация, применение функций)

In [3]:
[1,2,3,4] + [1,2,3,4]

[1, 2, 3, 4, 1, 2, 3, 4]

In [4]:
[i**2 for i in [1,2,3,4]]

[1, 4, 9, 16]

Как корректно загружать библиотеку?

In [5]:
import numpy as np
from IPython.display import display

In [6]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [7]:
%time for _ in np.arange(50): my_arr_2 = my_arr * 2

CPU times: user 49.3 ms, sys: 6.73 ms, total: 56 ms
Wall time: 76.7 ms


In [8]:
my_arr_2

array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

In [9]:
%time for _ in range(50): my_list_2 = [x *2 for x in my_list]

CPU times: user 1.69 s, sys: 489 ms, total: 2.18 s
Wall time: 2.21 s


## "Случайное зерно"
Зачем нужно фиксировать "случайное зерно"?

In [10]:
np.random.seed(42) 
###
'''
почему так любят число 42 в программировании:
Самый Главный Вопрос Жизни, Вселенной и Вообще 
https://www.youtube.com/watch?v=D5O0vqatpXg
'''
###
data = np.random.randn(3,4)
data

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986],
       [-0.23415337, -0.23413696,  1.57921282,  0.76743473],
       [-0.46947439,  0.54256004, -0.46341769, -0.46572975]])

### Наконец-то у нас есть "нормальные" оперрации с векторами и матрицами

In [11]:
data * 10

array([[ 4.96714153, -1.38264301,  6.47688538, 15.23029856],
       [-2.34153375, -2.34136957, 15.79212816,  7.67434729],
       [-4.69474386,  5.42560044, -4.63417693, -4.65729754]])

In [12]:
data + data

array([[ 0.99342831, -0.2765286 ,  1.29537708,  3.04605971],
       [-0.46830675, -0.46827391,  3.15842563,  1.53486946],
       [-0.93894877,  1.08512009, -0.92683539, -0.93145951]])

In [13]:
data.shape

(3, 4)

In [14]:
data.dtype

dtype('float64')

### Переходим от списка к матрице (массиву) - `array`

In [15]:
data_1 = [6, 75, 8, 10, 0, np.nan]
arr_1 = np.array(data_1)
display(arr_1)
print(arr_1)
arr_1.dtype

array([ 6., 75.,  8., 10.,  0., nan])

[ 6. 75.  8. 10.  0. nan]


dtype('float64')

In [16]:
data_2 = [[ 1, 2, 3, 4],[ 5, 6, 7, 8]]
arr_2 = np.array(data_2)
display(arr_2)
print(arr_2)
arr_2.dtype

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

[[1 2 3 4]
 [5 6 7 8]]


dtype('int64')

In [17]:
arr_2.ndim

2

In [18]:
arr_2.shape

(2, 4)

In [19]:
arr_1.dtype

dtype('float64')

In [20]:
arr_2.dtype

dtype('int64')

### Разные нулевые массивы

In [21]:
zer = np.zeros([2,5])
emp = np.empty([2,5]) #не рекомендую ...
display(zer)
display(emp)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### Разные полезные команды

In [22]:
np.arange(110)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109])

In [23]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
data_3 = [[ 1, 2, 3],[ 4, 5, 6],[ 7, 8, 9]]
display(data_3)
np.ones_like(data_3)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

### Преобразование типов данных внутри NumPy

In [27]:
arr_1 = np.array([1, 2, 3], dtype=np.float64)
arr_1

array([1., 2., 3.])

In [28]:
arr_1.dtype

dtype('float64')

In [29]:
arr_2 = np.array([1, 2, 3], dtype=np.int32)
arr_2

array([1, 2, 3], dtype=int32)

In [30]:
arr_2.dtype

dtype('int32')

In [31]:
arr_3 = np.array([ 1, 2, 3, 4, 5])
arr_3.dtype

dtype('int64')

In [32]:
arr_4 = arr_3.astype(np.float64)
arr_4.dtype

dtype('float64')

In [33]:
arr_5 = np.array([ 3.6, 4, -5.8, 10.2, 18.5, -2.5, 0.3])
arr_5

array([ 3.6,  4. , -5.8, 10.2, 18.5, -2.5,  0.3])

In [34]:
arr_5.astype(np.int32)

array([ 3,  4, -5, 10, 18, -2,  0], dtype=int32)

In [35]:
arr_6 = np.array(['1.25', '18', '-3.2', '42.1'])
arr_7 = arr_6.astype(float)
arr_7

array([ 1.25, 18.  , -3.2 , 42.1 ])

In [36]:
arr_7.dtype

dtype('float64')

### Преобразование по образцу

In [37]:
int_array = np.arange(10)
display(int_array)
calibre = np.array([0.22, 0.23, -0.45])

int_array.astype(calibre.dtype)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

Базовые типы данных в NumPy:
https://numpy.org/devdocs/user/basics.types.html

# Работа с матрицами

### Сравнение

In [38]:
arr = np.array([[0,2,3],[4,5,6]])
arr

array([[0, 2, 3],
       [4, 5, 6]])

In [39]:
arr2 = np.array([[0., 12., 3.],[ 2., 5., -2.]])
arr2

array([[ 0., 12.,  3.],
       [ 2.,  5., -2.]])

In [40]:
arr > arr2

array([[False, False, False],
       [ True, False,  True]])

In [41]:
0 == 0.

True

### Срезы

In [42]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
arr[1:3]

array([1, 2])

In [44]:
arr[3:6]

array([3, 4, 5])

In [45]:
arr[6:10]

array([6, 7, 8, 9])

In [46]:
arr[5:8]

array([5, 6, 7])

In [47]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [48]:
### Внимание! Вспоминаем про ссылки на списки
arr_slice = arr[5:8]
display(arr_slice)
arr_slice[1] = 123456

display(arr_slice)
display(arr)

array([12, 12, 12])

array([    12, 123456,     12])

array([     0,      1,      2,      3,      4,     12, 123456,     12,
            8,      9])

In [49]:
arr2d = np.array([[ 1, 2, 3], [ 4, 5, 6], [ 7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [50]:
arr2d[2][2]

np.int64(9)

In [51]:
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [52]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [53]:
arr2d[1,:2]

array([4, 5])

In [54]:
arr2d[:2,2]

array([3, 6])

In [55]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [56]:
arr2d[:2,1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### Особенность размерности

In [57]:
# матрица
display(arr2d[:2,1:])
arr2d[:2,1:].shape

array([[0, 0],
       [0, 0]])

(2, 2)

In [58]:
# вектор
display(arr2d[2])
arr2d[2].shape

array([7, 8, 9])

(3,)

In [59]:
# ?
display(arr2d[2,:])
arr2d[2,:].shape

array([7, 8, 9])

(3,)

In [60]:
# ?
display(arr2d)
display(arr2d[2:,:])
arr2d[2:,:].shape

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

array([[7, 8, 9]])

(1, 3)

In [61]:
# ?
display(arr2d[:,:1])
arr2d[:,:1].shape

array([[1],
       [4],
       [7]])

(3, 1)

In [62]:
# ?
display(arr2d[1,2])
arr2d[1, 2].shape

np.int64(0)

()

In [63]:
np.dot(arr2d[:,:1],arr2d)

ValueError: shapes (3,1) and (3,3) not aligned: 1 (dim 1) != 3 (dim 0)

In [64]:
arr2d[:,:1].T.shape

(1, 3)